### ISSUE TITLE
Code:1, Type:Warning, Msg:The concurrency of database:0 with 3 exceeds the concurrency of hardware:2

### ISSUE THREAD

**Issue by JennieZhang1991** [Tencent/wcdb#204]
### 对应的 WCDB 语言 ( The language of WCDB )

 Objective-C

### WCDB 的版本号 ( The version of WCDB )
v1.0.5

### WCDB 的平台 ( The platform of WCDB )

iOS

短时间内执行多次
`- (BOOL)updateRowsInTable:(NSString *)tableName
             onProperties:(const WCTPropertyList &)propertyList
               withObject:(WCTObject *)object
                    where:(const WCTCondition &)condition`

提示
**[WCDB]Code:1, Type:Warning, Msg:The concurrency of database:0 with 3 exceeds the concurrency of hardware:2**

发现有部分数据没有更新成功……

WCDB不是线程安全的么

**Comment by RingoD** [comment]
认真读下提示...

**Comment by aidmony** [comment]
Hi there, I have a follow up question on this issue. 

Do you have a particular reason for setting s_maxConcurrency = 64 in HandlePool? 

I am asking because there is a max connection limit on the Sqlite side (sqlite3_open would fail if exceeds that limit), and want to know how you guys handle such extreme case gracefully. 

Since sqlite3_open is only called when generating a new "handle" in wcdb, I tried to simulate the case by dispatch_async a lot of "SELECT" tasks (e.g. the one in sample_chaincall_main.mm) . I am able to hit that "The concurrency of database exceeds the max concurrency" error by setting s_maxConcurrency = 63, but never could hit it for 64. Very curious on why it is that. Appreciated!

**Comment by RingoD** [comment]
@aidmony 
Actually, there is no concurrency limit of WCDB's handle pool. But typically, it's generally that we should add a upper limit to avoid unexpected problems.
So, this upper limit should be never reached in common use.

As an example, If someone run more than 64 threads to do a WCDB operation, it always results in a wrong way for using it.

As for why 64, I remember that there is a bug in old version of iOS while threads exceeds 64. Maybe you can google it.

The test case is now in [testConcurrencyExceeds](https://github.com/Tencent/wcdb/blob/dev/objc/testcase/test/crud/WTCMultithreadTests.mm) of `dev` branch, which will be merged into `master` in next release.

**Comment by aidmony** [comment]
Thanks a lot for helping out!

**Comment by zhanghesheng** [comment]
- (BOOL)updateRowsInTable:(NSString *)tableName onProperties:(const WCTPropertyList &)propertyList withObject:(WCTObject *)object where:(const WCTCondition &)condition 类似同样的问题,比如在同一线程连续调用以上方法，会出现不能及时调用到flowBack方法，m_aliveHandleCount不断++，进而出现满足if (m_aliveHandleCount > s_maxConcurrency)而导致"The concurrency of database exceeds the max concurrency"，导致数据更新失败，请问如何更好的处理这个问题 @RingoD
