### ISSUE TITLE
Memory SSD speed

### ISSUE THREAD

**Issue by JunyiXie** [Tencent/wcdb#294]
### The language of WCDB

> e.g. Objective-C, Swift or Java 

### The version of WCDB

> e.g. v1.0.5

### The platform of WCDB

> e.g. iOS, macOS or Android

### The installation of WCDB

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

> `WCDB does not support the creation of an in-memory database. Since most of the disk media for mobile platforms are SSDs, their performance is not significantly different from that of pure memory. At the same time, the in-memory database consumes a large amount of memory, resulting in FOOM.`

Has it been tested and has the corresponding test results supported?

thanks

**Comment by RingoD** [comment]
No, we did not provide a benchmark for this. (or maybe you can do it by yourself)

Actually, the more important thing is that in-memory database uses too much memory so that your app may easily be killed in mobile device.
On the other hand, dictionary can be replacement in most cases. So I don't think it's necessary.

But if it's an important feature for most of developers, we will add it too.
