### ISSUE TITLE
Hope Can Support Subquery function

### ISSUE THREAD

**Issue by zeR0Lu** [Tencent/wcdb#337]
### The language of WCDB

> e.g. Swift

### The version of WCDB

> e.g. v1.0.6.2

### The platform of WCDB

> e.g. iOS

### The installation of WCDB

> e.g. Cocoapods

### What's the issue?

> Post the outputs or screenshots for errors.
> UPDATE CacheMediaTable SET downloadedSectionNum=SELECT (MAX(downloadedSectionNum) + 1) FROM CacheMediaTable WHERE ((mediaID = '32') AND (userID = '123')) WHERE ((mediaID = '32') AND (userID = '123'))
> Explain what you want by example or code **in English**.
I hope that you can add "()" to the condition of the SQL statement to achieve the effect of the subquery.

**Comment by zeR0Lu** [comment]
Use This SQL "UPDATE CacheMediaTable SET downloadedSectionNum=(SELECT (MAX(downloadedSectionNum) + 1) FROM CacheMediaTable WHERE ((mediaID = '32') AND (userID = '123'))) WHERE ((mediaID = '32') AND (userID = '123'))"  success to excute

**Comment by RingoD** [comment]
Sorry, but I don't understand what your issue is.

**Comment by zeR0Lu** [comment]
let column = property.asColumn()
        
        let add = StatementSelect().select(expression).from(table.rawValue).where(_where)
        
        let updateSet: StatementUpdate.ValueType = (column, add)
        
        let sql = StatementUpdate().update(table: table.rawValue).set(updateSet).where(_where)
        
        print(sql.description)
        do {
            try database?.exec(sql)
        } catch {
            print(error)
        }

This is My code, it report an error the same as my issue

**Comment by RingoD** [comment]
So? What's the error?

**Comment by RingoD** [comment]
No reply.

**Comment by leonylcatwork** [comment]
I think the problem is subquery was not correctly combined in the update statement, in the 'set' clause there is not brackets surround the subquery so that compiler raised error 'near "SELECT": syntax error'.

UPDATE CacheMediaTable SET downloadedSectionNum=SELECT (MAX(downloadedSectionNum) + 1) FROM CacheMediaTable WHERE ((mediaID = '32') AND (userID = '123')) WHERE ((mediaID = '32') AND (userID = '123'))

should have been 

UPDATE CacheMediaTable SET downloadedSectionNum=(SELECT (MAX(downloadedSectionNum) + 1) FROM CacheMediaTable WHERE ((mediaID = '32') AND (userID = '123'))) WHERE ((mediaID = '32') AND (userID = '123'))
