### ISSUE TITLE
运行 swift build 报错 no manifest for version 1.0.7

### ISSUE THREAD

**Issue by miewx** [Tencent/wcdb#396]
ubunut
运行
swift package init --type executable 
新建项目
修改Package.swift添加依赖
然后运行 swift build 报错

$ cat Package.swift

```
// swift-tools-version:4.2

import PackageDescription

let package = Package(
    name: "find",
    dependencies: [
        // Dependencies declare other packages that this package depends on.
        // .package(url: /* package url */, from: "1.0.0"),
        .package(url: "https://github.com/vapor/vapor.git", from:"3.1.0"),
        .package(url: "https://github.com/Tencent/wcdb.git",from:"1.0.7"),

    ],
    targets: [
        // Targets are the basic building blocks of a package. A target can define a module or a test suite.
        // Targets can depend on other targets in this package, and on products in packages which this package depends on.
        .target(
            name: "find",
            dependencies: [
                "Vapor",
                "WCDBSwift"

            ]
        ),
        .testTarget(
            name: "findTests",
            dependencies: ["find"]),
    ]
)

```

https://github.com/Tencent/wcdb.git @ 1.0.7: error: https://github.com/Tencent/wcdb.git has no manifest for version 1.0.7

![image](https://user-images.githubusercontent.com/26247733/46127432-37e36380-c263-11e8-928d-3a8ad06eb966.png)

**Comment by RingoD** [comment]
I think Swift package is not supported by WCDB currently since we do nothing to integrate it.
Maybe it could be fixed by simply adding a `Package.swift` file at the root directory the repo or something else? 
I don't know. I need some time to read the documentation of Swift package.

There is a promise that it will be supported when the next major version is released. But for now, this is not my priority.

Actually, if you already have the knowledge about Swift package, it's encouraged to submit a PR. And after that, we will tag a new version for Swift package.
