### ISSUE TITLE
How to transform property individually with ORM similarly to Mantle

### ISSUE THREAD

**Issue by LatteCat** [Tencent/wcdb#409]
### The language of WCDB
> Objective-C
### The version of WCDB
>  v1.0.7.5
### The platform of WCDB
> iOS
### The installation of WCDB
> Cocoapods

### What's the issue?
How to make a property transform individually with ORM?

I have declared a class which contains a property **users** declared with `NSArray<NSString *>  *` type.  For now my resolution is saving the binary data into a column defined with `BLOB` type. It's not convenient to reveal the ray data in database file. (Maybe saving binary data into database with `BLOB` could lead a little bad performance)

I want to transform the binary data into a JSON Array String before it is saved to database.
Is there any approach to make it?
[Mantle](https://github.com/Mantle/Mantle) have supported this function.

At the same time, if I transform the users into a JSON Array  String before saving it into database, the performance and the size will be improved?

**Comment by RingoD** [comment]
I don't it is possible to transform binary data into column. As an example, `NSArray` may have variable number of columns.
BUT for your issue - reveal `BLOB` value in a human readable structure, JSON or other string literal type should be the easiest way to solve it, as you said.

**Comment by RingoD** [comment]
`WCTColumnCoding` is used to transform `NS-Type` to `NSData` or `NSString`, which can be learned in wiki.
As a global way, you can make `NSObject` conforms to `WCTColumnCoding`.

Actually, it's the default coding solution in WCDBSwift. But in ObjC, we use `NSCoding` instead JSON, since the latter one is not the default coding solution for this language.
