### ISSUE TITLE
BackupKit blocks write operations in WAL mode

### ISSUE THREAD

**Issue by shunix** [Tencent/wcdb#432]
### The language of WCDB

> Java

### The version of WCDB

> v1.0.6.2

### The platform of WCDB

> Android

### The installation of WCDB

> gradle

### What's the issue?

> I have enabled WAL on my database. I wonder if write operations will be blocked when *BackupKit.run()* is in progress.
> I've made some test, it seems that write operations from other thread won't be satisfied until *BackupKit* finished. 
> From my perspective, *BackupKit* only requires read access to database, it should not block other write operations in WAL mode.
> Any feedback is appreciated.

**Comment by John-He-928** [comment]
`BackupKit.run()` WILL block write operations at this time. This may be changed in the future.

**Comment by shunix** [comment]
Why this method block write operations, could you show the code?

**Comment by John-He-928** [comment]
`BackupKit.run()` acquires write (primary) connection when it starts. That's because we considered it should not allow write operations since they change the DB and cause an intermediate state. Reading different tables in backup is not an atomic operation. If write operations occur during backup, the consistency of the backup will be broken.

Consider such situation:
1. Start backing up table A;
2. Write operation changes table A and B at the same time, where B has a foreign key pointed to A;
3. Start backup up table B.

This will result in changes made to table B in step 2 is in the backup data, while changes made to A is not. Data recovered by this backup data may be unusable.

`BackupKit` and `RecoverKit` is designed to be breakable in any time when they are running. You may probably want to setup a `CancellationSignal` to them and break it whenever you need to write to the DB. Running backup in a `JobScheduler` (when the phone is charging and inactive) is preferred to make the backup progress smooth.

This behavior may be changed in the future if we can begin a "read transaction" during the backup, which makes the backup read a snapshot version of the DB.

**Comment by shunix** [comment]
Thank you for your prompt reply.
