### ISSUE TITLE
Crash in -[WCTSelectBase lazyPrepare] (WCTSelectBase.mm:74)

### ISSUE THREAD

**Issue by kudocc** [Tencent/wcdb#465]
### The language of WCDB

> Objective-C

### The version of WCDB

> v1.0.7.5

### The platform of WCDB

> iOS

### The installation of WCDB

> Cocoapods

### What's the issue?

Crash info:

EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000000

Call stack:

```
0  xxxxx                         0x1021d1f0c -[WCTSelectBase lazyPrepare] (WCTSelectBase.mm:74)
1  xxxxx                         0x1021d0b94 -[WCTSelect nextObject] (WCTSelect.mm:138)
2  xxxxx                         0x1021b2e94 -[WCTInterface(Convenient) getOneObjectOfClass:fromTable:where:] (WCTInterface+Convenient.mm:51)
```

Thanks for help

**Comment by RingoD** [comment]
Sorry, but with the lack of crash stack, I have no idea to work on it. Please provide the entire crash stack, including the stack of all threads and crash analysis. Or provide a project that can reproduce this crash.

**Comment by kudocc** [comment]
@RingoD  I downloaded the crash file in fabric and modify it to hide some sensitive info, thanks for you help.

[issue_331362_crash_f108b90801594016a8593d8b9cbe2bb8_DNE_0_v2.txt](https://github.com/Tencent/wcdb/files/2929033/issue_331362_crash_f108b90801594016a8593d8b9cbe2bb8_DNE_0_v2.txt)

**Comment by RingoD** [comment]
It an "exit crash".
When the app is exiting, some of the threads are still running. At the mean time, those static cpp variables, which is stack based memory, will enter the destructor. Then, a running thread visits the destructing or destructed memory, the crash happens.
Ones have no need to focus on it since it's already exiting, which means that users will not notice this crash.
In the next version, we will fix it by using heap based memory for static cpp variable.
