### ISSUE TITLE
编译成功，私有库验证出错，求解答

### ISSUE THREAD

**Issue by peppapedar** [Tencent/wcdb#858]
我创建了一个私有库，其中的导入了WCDB,工程编译没有问题，文件后缀也都改为了.mm
podspec文件里面是引用了wcdb版本如下：
`s.dependency 'WCDB','1.0.7.5'`
在我进行pod lib lint验证的时候却报错：
error: Since WCDB is an Objective-C++ framework, for those files in your project that includes WCDB, you should rename their extension .m to .mm.

这令人很费解，可以帮忙解答一下吗？

**Comment by hxming2919** [comment]
s.pod_target_xcconfig = { :CLANG_CXX_LANGUAGE_STANDARD =&gt; "c++11", :CLANG_CXX_LIBRARY =&gt; "libc++"}
添加xcconfig试试



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 王文哲 ***@***.***&gt;
发送时间: 2022年5月7日 09:54
收件人: Tencent/wcdb ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [Tencent/wcdb] 编译成功，私有库验证出错，求解答 (Issue #858)





 
我创建了一个私有库，其中的导入了WCDB,工程编译没有问题，文件后缀也都改为了.mm
 podspec文件里面是引用了wcdb版本如下：
 s.dependency 'WCDB','1.0.7.5'
 在我进行pod lib lint验证的时候却报错：
 error: Since WCDB is an Objective-C++ framework, for those files in your project that includes WCDB, you should rename their extension .m to .mm.
 
这令人很费解，可以帮忙解答一下吗？

**Comment by peppapedar** [comment]
谢谢@hxming2919
亲测添加了还是报一样的错.
`s.pod_target_xcconfig = {
    'CLANG_CXX_LANGUAGE_STANDARD' => "c++11", 
    'CLANG_CXX_LIBRARY' => "libc++",
}`

**Comment by Qiuwen-chen** [comment]
Add the --skip-import-validation option when you pod lint.
